version: "3"
services: 
    scala:
        build: ./docker/scala
        user: 1000:1000
        volumes: 
            - .:/home/dev/dev-scala-with-docker
            - sbt-cache:/home/dev/.sbt
            - ivy2-cache:/home/dev/.ivy2
        working_dir: /home/dev/dev-scala-with-docker
        tty: true
volumes: 
    sbt-cache:
    ivy2-cache: